# Generated by Django 5.2.7 on 2025-11-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_profile_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
