# Generated by Django 5.2.7 on 2025-11-12 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_profile', models.BooleanField(default=True)),
                ('public_skills', models.BooleanField(default=True)),
                ('public_trades', models.BooleanField(default=False)),
                ('contact_option', models.CharField(choices=[('Everyone', 'Everyone'), ('People with mutual skills', 'People with mutual skills'), ('No one', 'No one')], default='Everyone', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
