# Generated by Django 5.2.7 on 2025-12-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_first_name_user_last_name_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
