# Generated by Django 5.2.7 on 2025-12-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('trade_proposal', 'Trade Proposal'), ('trade_accepted', 'Trade Accepted'), ('trade_active', 'Active Trade'), ('trade_completed', 'Trade Completed'), ('system_alert', 'System Alert')], max_length=50),
        ),
    ]
