# Generated by Django 5.2.6 on 2025-10-11 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeProposal',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('proposal_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('countered', 'Countered')], default='pending', max_length=20)),
                ('last_status_update', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='listings.skilllisting')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_made', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_received', to=settings.AUTH_USER_MODEL)),
                ('skill_desired_by_proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_desired', to='skills.skill')),
                ('skill_offered_by_proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_offered', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('terms_agreed', models.TextField()),
                ('skill1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_skill1', to='skills.skill')),
                ('skill2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_skill2', to='skills.skill')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_user2', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade', to='trade.tradeproposal')),
            ],
        ),
    ]
