# Generated by Django 5.2.7 on 2025-12-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_portfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllisting',
            name='portfolio_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
