# Generated by Django 5.2.7 on 2025-12-17 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_portfolioimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimage',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='listings.skilllisting'),
        ),
    ]
